### PR TITLE
Alert for updates mapbox studio

### PR DESCRIPTION
**Pull request by camilleanne**
re #690 
screen shot 2014-08-21 at 2 17 28 pm

### CODE REVIEW

**Comment by camilleanne** [comment]
@yhahn like a full screen thing a la https://github.com/mapbox/mapbox-studio/blob/master/templates/oauth.html ?

**Comment by yhahn** [comment]
Yep.

The other thing I think we could look at is merging the update version script into the end of the build/packaging script itself so that travis automatically updates this for us when the gitsha matches a tag.

**Comment by camilleanne** [comment]
@samanpwbb @yhahn Can't seem to get the blue of https://github.com/mapbox/mapbox-studio/blob/updatealert/templates/update.html to extend all the way down to the bottom. thoughts?

**Comment by samanpwbb** [comment]
@camilleanne adding the class to the body should do the trick - you're seeing the background color of the body overflowing. Alternatively you can set the fill-blue div to 100% height and width with like a `pin-left col12`.

**Comment by yhahn** [comment]
@camilleanne looks good, one issue atm for this is that it's hard to test -- I'm guessing you've been going into your package.json and hacking it to 0.0.2 manually or so to test?

I think we could eventually look at moving the versionCheck into a `lib/version.js` file or so so that it's somewhat testable. It'll probably need to take optional params to override the latest version URL and package.json source path to mock different version testing scenarios. Functionality you've written that seems worth testing:
- HTTP I/O errors are ignored
- whitespace is stripped from latest/package.json version strings

**Comment by camilleanne** [comment]
@yhahn added tests and moved things around

**Comment by yhahn** [comment]
@camilleanne so good

**Pull request merged**
