### PR TITLE
[notready] mapnik3

### PR DESCRIPTION
**Pull request by yhahn**
- [x] windows testing (update vcredist)
- [x] windows installer (update vcredist)
- [x] manual testing

### CODE REVIEW

**Comment by samanpwbb** [comment]
Added better reference for expressions:
screen shot 2014-10-22 at 2 46 40 pm
screen shot 2014-10-22 at 2 46 35 pm

@springmeyer let me know if the copy I'm using needs to be adjusted.

**Comment by springmeyer** [comment]
@samanpwbb looks good. What about using `marker-file: url("/path/to/[some_field].svg");`. In the case of expressions with files the field value is used to complete a file path vs say `marker-opacity:[some_field];` which is evaluated to a floating point number. We could say this explicitly with an `Evaluates to ....` section of the doc perhaps?

**Comment by springmeyer** [comment]
overall: this is ready to go. I'm doing a quick test of whether we can improve the windows 64 bit install location (https://github.com/mapbox/mapbox-studio/commit/28361619f79e042f9bef50f9b450b6ab80b667aa), but nothing is blocking here.

**Comment by springmeyer** [comment]
closing, now over at https://github.com/mapbox/mapbox-studio/pull/955

**Pull request closed without merging**
