### PR TITLE
User fonts

### PR DESCRIPTION
**Pull request by samanpwbb**
Does four things:
- Packages font files with .tm2z
- Smaller font display in sidebar to fix broken fonts (sort of unrelated)
- Adds documentation in `advanced-features` on using custom fonts
- Adds note about custom fonts in font sidebar:
  
  screen_shot_2014-10-28_at_6_14_33_pm

cc: @yhahn

### CODE REVIEW

**Comment by wboykinm** [comment]
:+1: \* 1000

**Comment by rossmeissl** [comment]
:pizza:

**Comment by aemonm** [comment]
Possible to use font-hosting platforms with this? Like Typekit?

**Comment by samanpwbb** [comment]
@aemonm not at the moment. You'll need to provide the font file directly.

**Comment by wboykinm** [comment]
@samanpwbb Is this currently only available on the `mb-pages` branch? I'm getting this error with a current install from `master`:

`Failed to find font face 'Whitney Book' in style 'road_label' in TextSymbolizer`

I've added .OTFs to the project in subfolder `fonts` and pointed the map elements `font-directory` parameter at it.

**Comment by wboykinm** [comment]
@samanpwbb Actually cancel that thought -  the error seems related to a bug in my .otf, and the other custom typefaces have loaded up perfectly with the package. Thanks for adding this!

**Comment by springmeyer** [comment]
@samanpwbb - does this (https://www.mapbox.com/mapbox-studio/advanced-features/) need a link off the home page?

**Pull request merged**
