### PR TITLE
Mbbase

### PR DESCRIPTION
**Pull request by samanpwbb**
Todo: 
- [x] Style x-ray popup
- [x] Fix autocomplete dropdown (tristen)
- [x] Ensure all class event triggers are working
- [x] Smooth transition when opening data tab
- [x] Codemirror source editor problem (https://github.com/mapbox/tm2/issues/166)

### CODE REVIEW

**Comment by samanpwbb** [comment]
This is ready for review.

**Comment by samanpwbb** [comment]
@ian29 brought up new issues to fix: 
- [x] Codemirror visibility weirdness when using display:none; on codemirror.
- [x] Bigger click area for source listing  
- [x] Cleaner data listing in style mode

**Comment by yhahn** [comment]
\o/

**Comment by tristen** [comment]
YUS!

**Comment by ian29** [comment]
:pray:

**Pull request merged**
