### PR TITLE
Interaction tab help

### PR DESCRIPTION
**Pull request by tristen**
This commit clarifies the tooltip tab and pulls variables for each vector source and inserts this into the code
### Help

info
### Populate

populate

### CODE REVIEW

**Comment by samanpwbb** [comment]
It is unclear how the dropdowns work in this UI:
screen shot 2014-03-18 at 12 30 28 pm

**Comment by samanpwbb** [comment]
The documentation should include an example, showing off the syntax, like: 
screen shot 2014-03-18 at 12 32 10 pm

Some more complex examples would also be helpful. User should be able to utilitze this feature without digging through external docs

**Comment by samanpwbb** [comment]
**IF** the country dropdown is an actual selection but the layer dropdown is just for autofill, we need something like:
screen shot 2014-03-18 at 12 32 57 pm

OR we need to clarify that only one layer can be active at a time. 

Right now I can end up with this situation, which is confusing:
screen shot 2014-03-18 at 12 34 54 pm

**Comment by tristen** [comment]
Gone for a more simpler approach here that exposes help and doesn't contain data variables in a select element:

tm1-approach

**Comment by samanpwbb** [comment]
1. What if the 'layer to use for interaction data' dropdown felt more like a heading? I think this needs to play a stronger role, because that dropdown is what defines the users' state.
2. I know this seems obvious now, but I would love to still have a hint button with examples inside:

> "Select a layer from the dropdown, and then place an attribute in brackets like {{{attribute}}}. You can combine tags with plain text. For example, `{{{featuretype}}} is {{{depth}}} meters deep` would result in a popup that read: "lake is 300 meters deep" when hovering over a feature with `featuretype:lake` and `depth:300`.

**Pull request merged**
