### PR TITLE
UI addlayer updates

### PR DESCRIPTION
**Pull request by GretaCB**
@samanpwbb @ajashton @ian29 
Interested in your input before merging. Any thoughts, concerns, suggestions are greatly appreciated. 

After integrating mapnik-omnivore into TM2, this allowed for simplifying how users add layers/files (KML, gpx, shape, CSV, geojson). Mapnik-omnivore can detect the filetype, layers, and other spatial info about a file. Therefore, TM2 no longer has to ask the user for certain information. This information is auto-populated into the proper modal and settings (for example: projection, maxzoom, and all layers are set automatically). Postgis and SQLite files are added the same as before, but they will hopefully be up to speed soon.
## UI Review:

I changed the `#addlayer` form a bit. 

Before:
screen shot 2014-06-05 at 6 45 48 pm

After:
screen shot 2014-06-05 at 6 47 52 pm

Now, once the file is selected:
- the UI will display the proper modal with projection and filepath
- if there are multiple layers in one file, the UI will display the main project modal (#) showing all layers
- the Fields modal will be populated
- you can zoom-to-layer using the crosshair icon next to the layer (local sources only). At the moment, layers that come from the same source will have the same lat/lon for zoom-to-layer since there is no way to retain each layer's center/extent (https://github.com/mapbox/tm2/issues/393)
- if the new source's maxzoom is greater than the project's current maxzoom, it favors the higher zoom (maxzoom for each new source is coming from `mapnik-omnivore`, which is set based on the size of the file)

### CODE REVIEW

**Comment by samanpwbb** [comment]
This is great! I will test this out later.

A few things based on above screenshot:
- Right now it looks more like a form where I need to start from the top and move to the bottom, but in actuality there are two separate actions on this screen: either browse for a file source, or add a database source, both resulting in a new layer. How can the UI text and the layout direct user in one of the two directions more clearly?
- Don't need 'database' labels on the radio buttons any more.
- Use the [button with input](https://www.mapbox.com/base/styling/buttons/) style for the database file name so the right keyline on the input dissapears and the left roundedness on the button straightens out.

**Comment by ajashton** [comment]
In general I love the workflow, great improvement. Some thoughts:
- Seems like database layers have to be Web-mercator now? I tried adding a WGS84 PostGIS layer and nothing showed up
- @yhahn doesn't have me totally convinced that the projection field should really be un-editable, but I'll see how it goes. (It's pretty common for files to have missing or incorrect projection definitions, and sometimes you [intentionally want to override things](http://blog.spatialnetworks.com/post/2011/12/mapping-experiments-antarctica/))
- We'll want to fix https://github.com/mapbox/tm2/issues/95 soon

**Comment by ajashton** [comment]
Went for a walk and ready to argue with myself now ;) 
- broken projections can (should, really) be fixed in the file
- advanced projection hacking can still happen by editing the yml or editing the file 
- PostGIS can be reprojected in the query but we could probably still improve things there

**Comment by GretaCB** [comment]
@samanpwbb 
Totally, I thought about the split as well. Would it be too jumpy to have a link to another modal to separate out the database options? Or maybe have the two different options side-by-side, instead of top-to-bottom. I'll whip something up right now with your suggestions.

@ajashton 
In mapnik-omnivore, projections for shape files are detected from the adjacent `.prj` file (https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasourceProcessor.js#L236-259). 
But for all other filetypes, they are set to defaults (https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasourceProcessor.js#L79-89), based on Mapnik's behavior. Basically setting them all to WGS84 off the bat. 

I haven't touched projection stuff with PostGIS or SQLite yet, but will be playing around with that soon using node-gdal.

I agree, it would be cool to be able to play around with different projections, maybe with a drop down of some kind, similar to TM1. And more advanced overrides can be done within the yml. But any projections used in tilemill must be Mapnik-friendly projections only, if I'm not mistaken? 

Regarding https://github.com/mapbox/tm2/issues/95, going to ponder this today.

**Comment by GretaCB** [comment]
@samanpwbb 
A bit rough, but separated the options into separate boxes:

screen shot 2014-06-06 at 11 15 10 am

**Comment by samanpwbb** [comment]
@GretaCB here's a sketch:
screen shot 2014-06-06 at 12 40 12 pm

Don't necessary treat this as a final layout, but a flow suggestion. Start with a toggle, which basically asks the user for their intent. Once they've made a decision, we can provide a more focused UI.

I would try to use the _same_ copy and visual language for the 'submit' button across the database and data source tabs. So, same color button, same copy text on button. For bonus points, try to put both buttons in the exact same place on both tabs.

I really like the way you're reading file names for layer titles of file sources, which allows for one click create a source from file browser.

**Comment by yhahn** [comment]
Another approach to this would be to hit https://github.com/mapbox/tm2/issues/95 first, then return to this UI. It would let you eliminate the form field/layer naming requirement of PostGIS/SQLite and let the UI stay more minimal/focused:

```
[________________] add file

Need to add a PostGIS or SQLite database?
```

where the DB options are just links that create a layer and let you name it after.

**Comment by samanpwbb** [comment]
> where the DB options are just links that create a layer and let you name it after.

:+1: this would be swell.

**Pull request closed without merging**
