### PR TITLE
PostGIS manual page for Studio docs

### PR DESCRIPTION
**Pull request by amyleew**
**_[updated with edits]_**  

@heyitsgarrett @ajashton - Guide to PostGIS Manual ready for review. Edits welcome, @katydecorah @geografa would love your :eyes: as well. 

postgis manual - mapbox 1

cc @yhahn @ian29

### CODE REVIEW

**Comment by wboykinm** [comment]
This is fabulous.

**Comment by heyitsgarrett** [comment]
This looks great, @amyleew - is it linked to from anywhere within the Studio docs? It's worth considering how it fits into the Source Manual, Source Quickstart space - @katydecorah I'd love your opinion on organization here.

**Comment by amyleew** [comment]
Yes @heyitsgarrett, I planned for it to be linked alongside other Studio docs in the _manual_ and _quickstart_ format, as **PostGIS Manual**. A color + icon treatment can be added as well. @katydecorah thoughts?

I plan to write a follow-up **PostGIS Quickstart** in the coming weeks.

image

**Comment by katydecorah** [comment]
@amyleew @heyitsgarrett Since this topic is dealing with data sources and PostGIS is mentioned in the Source manual, I recommend that it should fall under the same color/category as the Source quickstart and manual:

image

Also, a link to the PostGIS guide would be great in this section: https://www.mapbox.com/mapbox-studio/source-manual/#postgis

**Comment by amyleew** [comment]
@heyitsgarrett @katydecorah That's a fantastic idea! Do you guys think a PostGIS quickstart would be helpful here as well?

**Comment by katydecorah** [comment]
@amyleew I think it a PostGIS quickstart would be great. As I read through the manual (which is fantastic!), I started to wish I had sample data to follow along with. That's what I like about the Style and Source quickstarts -- they give sample data and walk you through it. I think it would be a great companion piece to the manual.

**Pull request merged**
