### PR TITLE
Nicedocs

### PR DESCRIPTION
**Pull request by samanpwbb**
Addresses https://github.com/mapbox/tm2/issues/462 -

Realized that we really do need a manual and cutting it isn't sufficient. Linking to online docs is a bad idea at this point, because there aren't any.

One nice this about this is that it saves your tab state - often I find myself _either_ wanting to look at fonts a lot _or_ carto reference a lot - so this is now more convenient.
- [ ] Now that I have a layout pinned down, I'm going to work on cleaning up the actual manual. This might need a more focused experience.
- [ ] Cleanup walkthrough to match design changes

@yhahn you see promise in this direction?

### CODE REVIEW

**Comment by yhahn** [comment]
@samanpwbb I htink your initial reaction here and those of users are relevant: https://github.com/mapbox/tm2/issues/462.

> Linking to online docs is a bad idea at this point, because there aren't any.

There's obviously a different way to fix this.

**Comment by samanpwbb** [comment]
👍 - you fine with totally cutting the manual here? Bit of A sub-optimal reading experience I'd say and I don't think we need it. OSM bright should sort of do the initial immersive learning on boarding and we just just let it be known that full external docs exist.

**Comment by yhahn** [comment]
Yeah, unless you have some really brilliant approach to the copy...

Let's lean on the walkthrough and good starting style/comments next and see where we go from there.

**Comment by samanpwbb** [comment]
Closing. Replaced with work in `layout-revamp3`.

**Pull request closed without merging**
