### PR TITLE
Print/Export view to Style view

### LINKED ISSUE #553: Move print UI into style editor
A pain point is switching contexts between the styling interface (i.e. hiding or showing certain styles or labels) and the 'Export Image' pane.

Ideally, we preserve state (zoom level, bounding box, crop) as you toggle between modes without having to rely on the bookmarking interface, which doesn't suffice for fast switching.

### LINKED ISSUE #554: Export Image: Remember previous settings
Related: #553 

Remember settings (bounding box size, location, crop, resolution, etc) when reentering this state from the style interface.

### PR DESCRIPTION
**Pull request by camilleanne**
fixes #553 
fixes #554 
the print/image export ui now lives in the style view -- can be accessed by the little button at the top 
print

~~Only thing that I'm not keen on is this toggle styling which I haven't figured out how to change? @samanpwbb any thoughts? is this a new base bug?~~
fixed

### CODE REVIEW

**Comment by yhahn** [comment]
@camilleanne this is sick

**Comment by samanpwbb** [comment]
Ya base bug - can you issue it there?

**Comment by camilleanne** [comment]
AppVeyor is being a brat -- thoughts on anything I can do to fix it? Keeps failing on npm install or just cloning the repo: https://ci.appveyor.com/project/Mapbox/mapbox-studio/build/1.0.72

or shall I mosey on?

**Comment by springmeyer** [comment]
The `fatal: unable to access` on git clone you can ignore. But yeah, its annoying and getting more common on appveyor it seems: http://help.appveyor.com/discussions/problems/588-random-fetch-error-using-git-on-a-github-repository

**Comment by heyitsgarrett** [comment]
giphy

**Pull request merged**
