### PR TITLE
Mapbox Studio --> Mapbox Studio Classic

### PR DESCRIPTION
**Pull request by lyzidiamond**
- [x] A simple find/replace for Mapbox Studio --> Mapbox Studio Classic
- [ ] @lyzidiamond works with @springmeyer to do a simple find/replace for mapbox-studio --> mapbox-studio-classic (so I don't break anything)

On 9/15, this PR will be merged and we will rename the repo `mapbox-studio-classic`.

/cc @tmcw

### CODE REVIEW

**Comment by springmeyer** [comment]
Sounds good @lyzidiamond - travis is should start passing in your branch if you grab the latest from master (my fault).

**Comment by bsudekum** [comment]
@BergWerkGIS @yhahn I just updated the build process to account for the new name. This is minimally invasive and does not change the name of the app running on your machine. Want to take a look at https://github.com/mapbox/mapbox-studio/commit/9e15d1498c977f8562e07a7871c9df2ae98ce3c7 ?

Update: https://github.com/mapbox/mapbox-studio/pull/1451#issuecomment-140236607

**Comment by scothis** [comment]
is it ok that CI is failing?

**Comment by lyzidiamond** [comment]
@scothis per chat with @springmeyer last week:

> I should have just fixed master https://travis-ci.org/mapbox/mapbox-studio/builds/79380379

merging in master should make travis happy!

**Comment by scothis** [comment]
@bsudekum can you take a look at this test failure https://travis-ci.org/mapbox/mapbox-studio/jobs/80293959#L1726

**Comment by bsudekum** [comment]
@lyzidiamond I merged master in already.

appveyor is failing because of https://github.com/mapbox/mapbox-studio/commit/9e15d1498c977f8562e07a7871c9df2ae98ce3c7#diff-180360612c6b8c4ed830919bbb4dd459R4 and won't pass until the repo has changed it's name.

Looking into travis errors now.

**Comment by bsudekum** [comment]
Per discussion with @scothis, we're going to rely on github.com url redirects for publish processes.

**Comment by wilhelmberg** [comment]
@bsudekum @lyzidiamond 

AppVeyor could be made pass by overriding the clone directory via:

```
clone_folder: c:\projects\myproject
```

http://www.appveyor.com/docs/appveyor-yml

Also noting that [v0.2.8-alpha](https://github.com/mapbox/mapbox-studio/tree/v0.2.8-alpha) is the current development branch.
Could you create another classic-PR and see that it can be merged with `v0.2.8-alpha`?

**Comment by wilhelmberg** [comment]
@bsudekum @lyzidiamond
change of plans.
no new PR necessary on your side .

just chatted with @yhahn @springmeyer @flippmoke :
We are going to merge `v0.2.8-alpha` into `mb-pages` first and then `classic`.

**Pull request merged**
