### PR TITLE
Find and replace

### PR DESCRIPTION
**Pull request by edenh**
Adds code search with find and replace.

screen shot 2014-03-06 at 6 22 46 pm

screen shot 2014-03-06 at 6 23 09 pm
- <code>Cmd-F</code> Find
- <code>Cmd-G</code> Find next
- <code>Shift-Cmd-G</code> Find previous
- <code>Cmd-Option-F</code> Find and replace
- <code>Esc</code> Clear match highlights

Closes https://github.com/mapbox/tm2/issues/118

### CODE REVIEW

**Comment by edenh** [comment]
cc @yhahn @samanpwbb @tristen

**Comment by tristen** [comment]
Awesome! A couple first impressions:
- I wish the search utility worked a little more like the browsers. If I hit return on a search query I'd still like the search bar to stick around and have the choice to dismiss it when I press a close button or hit Esc.
- We should remove the left keyline from the input.
- I wonder if there's a nice way to surface the key commands for search in a nice way. ie: 

screen shot 2014-03-07 at 10 24 56 am

**Comment by samanpwbb** [comment]
@edenh i checked this out, and it feels great. Merge in when you feel good about it.

**Comment by tmcw** [comment]
:+1: right now we're at CodeMirror 2.x, and we're on the cusp of http://codemirror.net/4/doc/upgrade_v4.html which should unlock some good editor stretch goals

**Comment by ajashton** [comment]
Cool. Took me a while to figure out Find & Replace, which is mapped to Ctrl-Shift-R on Linux. This means if you don't have the right part of the UI focused you might end up accidentally hard-refreshing the page - can/should we change this?

**Comment by edenh** [comment]
I fixed some bugs and added close and help buttons. Also, if you select text and <code>Cmd-F</code>, the input will start with that selection.

@ajashton I'm stumped on the linux keymap issue. Shouldn't it be the same as windows, which is Ctrl-Opt-F?

**Pull request merged**
