### PR TITLE
Save bookmarks to project yml

### PR DESCRIPTION
**Pull request by samanpwbb**
Follow up to https://github.com/mapbox/mapbox-studio/pull/661

Saves projects to config file. Looks like this (with a two entries). Modelled after https://github.com/mapbox/gazetteer

``` yaml
_prefs: 
  bookmarks: 
    - center: 
        - 32.06395559466043
        - -99.140625
      place_name: Cross Plains, 76443, Texas, United States
      zoom: 4
    - center: 
        - 50.20854899229104
        - -104.5184326171875
      place_name: Saskatchewan, Canada
      zoom: 7
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -104.5184326171875
  - 50.20854899229104
  - 7
description: ''
format: jpeg95
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Satellite Afternoon
source: "mapbox:///mapbox.satellite,mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - labels.mss
template: ''
```

### CODE REVIEW

**Comment by samanpwbb** [comment]
It would be better to save these to a separate, optional bookmarks config file. Easier to share, less possibility of corrupting projects.

**Comment by yhahn** [comment]
Agreed...

```
project.yml
project.xml
bookmarks.yml
```

?

**Comment by nickidlugash** [comment]
> bookmarks.yml

:+1:

**Comment by camilleanne** [comment]
Also thumbs up on `bookmarks.yml`  -- it's been requested for print/export stuff a couple of times.

**Comment by samanpwbb** [comment]
Replaced by https://github.com/mapbox/mapbox-studio/pull/693

**Pull request closed without merging**
