### PR TITLE
Cleanup styles + reformat default display

### PR DESCRIPTION
**Pull request by samanpwbb**
Reworked a lot of reference entries with better default displays + examples:

If type=uri, show examples:
screen shot 2014-09-04 at 12 55 26 pm

if options is array, list all options separately. Also, rename type from 'block' to 'keyword' (not sure if this is technically correct, but it makes more sense to me):
screen shot 2014-09-04 at 12 55 21 pm

if type=function, show examples of all available functions:
screen shot 2014-09-04 at 12 55 13 pm

If type=expression and serialization=content, show examples for both printing arbitrary text and using existing fields:
screen shot 2014-09-04 at 1 01 21 pm

All other type=expression parameters get both an expression and a number example:
screen shot 2014-09-04 at 12 54 56 pm

If type=color, show examples: 
screen shot 2014-09-04 at 12 54 49 pm

Co-ordinating with updates to Mapnik reference: https://github.com/mapnik/mapnik-reference/issues/67

Todo:
- [x] Add examples for most parameters.
- [ ] Fix tests

### CODE REVIEW

**Comment by samanpwbb** [comment]
@yhahn or @springmeyer can one of you give this a quick review to make sure I'm not doing anything too frail or just flat out inaccurate in my template. The one I'm nervous about is `if (p.serialization==='content')` - Not exactly sure what this means, but as it's implemented now, this only applies to shield-name and text-name.

I tried to re-write the entries to make all arguments parameters take discoverable, avoiding a need for external links or a thorough [values](https://www.mapbox.com/carto/api/2.3.0/#values) section.

**Comment by samanpwbb** [comment]
@yhahn this is ready.

**Comment by yhahn** [comment]
Per voice, going to wait for https://github.com/mapnik/mapnik-reference/pull/69/files to land.

**Pull request merged**
