### PR TITLE
enable "zoom-to-extent" for non file based layers again

### PR DESCRIPTION
**Pull request by wilhelmberg**
@springmeyer 
`zoom-to-extent` was working for filebased layers only(using `mapnik-omnivore`).

to determine layer extents this fix uses:
- `mapnik-omnivore` for file based layers
- `mapnik` for non file based layers.

### CODE REVIEW

**Comment by springmeyer** [comment]
This is a good step forward. However in testing it appears not to work yet. The `data` variable passed to `source.extent(data)` has an empty array for `Layer`:

``` json
{ _prefs: 
   { disabled: [],
     inspector: false,
     mapid: '',
     rev: '',
     saveCenter: true },
  attribution: '',
  center: [ 0, 0, 3 ],
  description: '',
  Layer: [],
  maxzoom: 6,
  minzoom: 0,
  name: '',
  id: 'tmpsource:///Users/dane/projects/mbstudio/node_modules/mapbox-studio-default-source',
  _tmp: 'tmpsource:///Users/dane/projects/mbstudio/node_modules/mapbox-studio-default-source' }
```

This means that the data returned from https://github.com/mapbox/mapbox-studio-classic/blob/cec96c696f5a0469340c7714c77462fd3aa4280e/lib/server.js#L580-L581 is not the actual extent of the data but rather the default because [this loop](https://github.com/mapbox/mapbox-studio-classic/blob/cec96c696f5a0469340c7714c77462fd3aa4280e/lib/source.js#L302-L329) never evaluates.

So I think what needs to happen is the `data` passed to `source.extent` needs to have more information about the datasource enough to actually ask mapnik about the extent.

**Comment by wilhelmberg** [comment]
Yeah, splitting my changes into 2 PRs broke it.
This PR doesn't work without https://github.com/mapbox/mapbox-studio-classic/pull/1514
Merged https://github.com/mapbox/mapbox-studio-classic/pull/1514 into this.
Want to try again?

**Comment by springmeyer** [comment]
Just pulled latest mb-pages into this branch: next action is to manually test this and make sure its working.

**Comment by springmeyer** [comment]
9ef9836 gets this working for unsaved sources. Next action is for @BergWerkGIS to test again to make sure it still works for him.

**Comment by wilhelmberg** [comment]
@springmeyer looking good, tried with
- topojson
- gpx
- geojson
- shape file
- postgis
- csv

**Pull request merged**
