### PR TITLE
Bookmarks

### PR DESCRIPTION
**Pull request by edenh**
Adds location bookmarks, which are preserved in style and source views.

bookmarks

### CODE REVIEW

**Comment by bleege** [comment]
Nice!

**Comment by kkaefer** [comment]
\o/ Best feature

**Comment by skorasaurus** [comment]
/me swoons.  Great work. I've wanted this in TM for years.

**Comment by jqtrde** [comment]
:heart:

**Comment by nickidlugash** [comment]
Woohoo, can't wait to try this out!

**Pull request merged**
