### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by samanpwbb**
This is a big redesign + CSS cleanup branch.

Todo:
- [x] Investigate issues with being unable to save new projects, not having access to xray tiles, not having access to print tiles. Could be dumb front end changes or more likely issues with tilelive/tilelive-vector module updates (cc: @yhahn) because these things seem broken in master for me as well. 
- [x] Quick port of source mode to new layout
- [x] Quick modal update
- [x] Update tests

Will update with screenshots/gifs tomorrow.

### CODE REVIEW

**Comment by yhahn** [comment]
@samanpwbb hrm, not seeing these issues on master, at least not any issues with x-ray tiles. Looks like print/image export is hidden/disabled for new projects on master -- maybe something to preserve for now in your refactor?

**Comment by samanpwbb** [comment]
Ya, just double-checked. These problems are on my end.

> Looks like print/image export is hidden/disabled for new projects on master -- maybe something to preserve for now in your refactor?

Ya, doing this:
screen shot 2014-06-30 at 11 09 14 am

**Comment by samanpwbb** [comment]
On track to merge this later today. Here's what everyone is in for:

## Style

style-mode

## Source

source

## Print

print

**Comment by ajashton** [comment]
:rocket: love it

**Comment by heyitsgarrett** [comment]
Massive. :100:

**Comment by nilshoerrmann** [comment]
This is a huge improvement making the interface much clearer.
Thanks a lot!

**Pull request merged**
