### PR TITLE
Add links to postgis-manual

### PR DESCRIPTION
**Pull request by amyleew**
@pdgoodman @heyitsgarrett - Ready to merge...

Added links to PostGIS manual on [Mapbox Studio Source Manual page](https://www.mapbox.com/mapbox-studio/source-manual/#postgis)

image

And footer navigation in Mapbox Studio section

image

/cc @geografa

### CODE REVIEW

**Comment by pdgoodman** [comment]
@amyleew - any next actions here? 

If you and @heyitsgarrett think this is ready to roll, let's merge.

**Comment by amyleew** [comment]
@pdgoodman  - Just two links to footer and Source Manual based on @katydecorah @heyitsgarrett feedback here https://github.com/mapbox/mapbox-studio/pull/1145#issuecomment-71289930 ... It's ready to merge!

**Comment by heyitsgarrett** [comment]
:+1:

**Comment by pdgoodman** [comment]
:rocket: @amyleew

**Pull request merged**
