### PR TITLE
Changes the Projects button (and occurences of 'Project(s)') to 'Styles ...

### PR DESCRIPTION
**Pull request by duncangraham**
...& Sources'

this change is because 'Projects' is a name we've given to things made with the web editor which have no connection to studio

### CODE REVIEW

**Comment by duncangraham** [comment]
😭

**Comment by duncangraham** [comment]
Hey @springmeyer I thought this happened. I must have gotten caught up with Helpscout tickets. If you get any free time could you let me know what I'm doing wrong so I can fix it?

**Comment by springmeyer** [comment]
@duncangraham - it looks like on travis job failed, but unrelated to your changes. I merged latest mb-pages just now and pushed - hopefully the next build will pass and we can merge this.

**Comment by duncangraham** [comment]
thanks for the help @springmeyer!

**Pull request merged**
