### PR TITLE
Export static ui

### PR DESCRIPTION
**Pull request by camilleanne**

### CODE REVIEW

**Comment by samanpwbb** [comment]
This is a great start. Lets aim to get this shipped soon and iterate after launch. 

Some things worth hitting before merge:
- Aim for consistency with how you're naming things in the UI. For example, consider renaming 'Print' to 'Image' in style mode. Then, rename 'Export Settings for Static Maps' to something like 'Export image'.
- Sentence case all the UI text. for ex, 'Return to Styling' -> 'Return to styling'
- I would cut the filename field. The browser handles this for users and it'll simplify the UI.
- Remove both the 'i' icons. The text makes it seem more complex than it is. If things aren't clicking for users, lets fix by making the UI more intuitive and self-explanatory.
- Rather than 'low','medium', and 'high' resolution labels, thoughts on just labeling these with their corresponding DPI values? Eliminates the need to explain this in a tooltip.
- What does the 'redraw' button do? I can't tell. It seems to just center the selection on the screen. Can we cut this?
- What's your justification for the drawer close button? It's confusing because after click, there's no way to re-open except via the existing control. 
- Export relies heavily on the zoom level of the map, but this isn't clear in the UI. I would add zoom level to the state display. At first, I thought the export would be based on the zoom level i was on when I clicked 'select area to export'. Just seeing a number change as I zoom would make this clear to me.
- To make the UI more focused, I would take this state display:
  screen shot 2014-06-12 at 12 24 23 pm
  
  make it more prominent and better organized. In particular, I would emphasize pixel dimensions and zoom level, de-emphasize % of max and simplify how you're displaying bounds (can the bounds UI visually reflect the info it contains? Icons + strategic form placement could help here. )

**Comment by camilleanne** [comment]
Thanks @samanpwbb. First pass:
I fixed the easy things (titles, resolution toggles, drawer close button), some of the others I'd like to talk through so I know where to go. I moved the box of attributes up to the top, not sure if that's the best way to emphasize it, also added zoom to the list.

Not sure about removing the % of max yet or how else to show it.

I removed the filename field-- I wonder if the filename then should contain information about the image that we just default to? e.g. style name, bounding box, zoom level, scale.

The drawer close button was just something I was using while working because I don't like how small the fullscreen icon is (and I didn't know it was there until young told me it was). 

Found a way around the redraw button. It was there (and has been replaced by submission on 'enter' keydown) so you could modify the coordinates and redraw the bounding box. I think it's important to be able to dump in a bounding box or center if you have coordinates already, however, center could go away in favor of using the geocoder and then reselecting within current view. Now it's a lot more subtle, but doesn't fix the issue of knowing if they can be edited, or 

> can the bounds UI visually reflect the info it contains? Icons + strategic form placement could help here.

You mean put forms on the corners of the bounding box? whoa.

Also, I would like to have part of the interface be 'bookmarking' bounding boxes so you could export several styles in the same area.

**Comment by samanpwbb** [comment]
Way better. Automatically checking for user input in the fields is much nicer. 

> You mean put forms on the corners of the bounding box? whoa.

Sure, worth experimenting with, but I don't think we have to go that far. For now, simple things like making bounds input 8/12 width and center intpu 4/12 width, side by side, could go a long way in relating these two elements to each other.

> I removed the filename field-- I wonder if the filename then should contain information about the image that we just default to? e.g. style name, bounding box, zoom level, scale.

Sounds like a good idea.

What's your reasoning behind the: "At zoom level [x] image is at 1% of size limit" widget? This confuses me. It is here to check how big my map will be at various sizes, but adjusting the zoom level doesn't influence the visible map or the export. I would limit the user's interactions with zoom level to _one_ way only: by zooming the map.

Relatedly, what do you think about not exposing the % of limit unless user actually goes over? This doesn't seem like useful info except when I've exceeded my allowance. Putting a warning that says something like, "image is 120% of max limit" over the export button if the size is too big could be an elegant solution to this problem.

**Comment by samanpwbb** [comment]
More minor points:
- Button text is too long. Find more concise ways of saying what you want to say.
- Use an H3 tag for your heading.
- Use the 'picture' icon instead of the 'print' icon and 'check' icon instead of 'polygon'

**Comment by samanpwbb** [comment]
_one last thing_ - I didn't realize I could resize the export box by selecting the corners. Handles would be nice.

**Comment by camilleanne** [comment]
@samanpwbb hah, I'm sorry, I forgot to check in the new handles.. I thought I was a crazy person looking at the pretty blue handles going, 'but... they're there...' then realized they're not being tracked in github.

**Comment by nickidlugash** [comment]
Very minor point: I think 'dpi' should be 'ppi' (pixels per inch).

**Comment by camilleanne** [comment]
@nickidlugash @samanpwbb Did a glance at another implementation of locking the aspect ratio for bounding boxes in leaflet (https://github.com/heyman/leaflet-areaselect/blob/master/src/leaflet-areaselect.js#L88-L101)-- this is a bit more than what I want to bite off right now, I'm going to merge this and we're going to keep talking about it :)

Any last thoughts before I pull the trigger?

**Comment by samanpwbb** [comment]
:ship:

**Comment by camilleanne** [comment]
tm2print21

for posterity

**Comment by nickidlugash** [comment]
@camilleanne looks great!

**Pull request merged**
