### PR TITLE
512

### PR DESCRIPTION
**Pull request by camilleanne**
Retina tiles for retina enabled screens. Normal resolution tiles for non-retina screens.

### CODE REVIEW

**Comment by yhahn** [comment]
Looks great -- @samanpwbb do you want to give this a whirl as a gut check?

**Comment by samanpwbb** [comment]
@camilleanne two things:
1. ~~The tiles aren't scaling for me ( i see retina tiles, but they're displaying at 256x256 not scaled down to at 128x128).~~ _Nevermind, this looks perfect on retina and on standard displays - i just needed to update tilelive-vector_.
2. This notice is confusing: 
   screen shot 2014-05-28 at 1 35 25 pm - the settings here should relate to the end product, not describe what you're just seeing in the editor. I would just remove the 'resolution' line completely. If you think it's important to inform users about this, then move it into the gray box (which has settings specific to the editor).

**Comment by camilleanne** [comment]
@samanpwbb cool-- wasn't sure about where that should go. I think it is a nice to know, and should be subtle.

**Comment by camilleanne** [comment]
this for now: 
screen shot 2014-05-28 at 8 04 53 pm

**Pull request merged**
