### PR TITLE
Style uploading

### PR DESCRIPTION
**Pull request by aaronlidman**
- [x] tests
- [x] npm publish updated mapbox-upload
- [x] better error handling
- [x] successful upload feedback?

### CODE REVIEW

**Comment by yhahn** [comment]
@aaronlidman want to use https://github.com/mapbox/mapbox-upload/archive/master.tar.gz in package.json for mapbox-upload atm?

Was just looking and getting a good release will need some more work per https://github.com/mapbox/mapbox-upload/issues/2

**Comment by aaronlidman** [comment]
:+1: thanks @yhahn 

@samanpwbb @nickidlugash Can you test out the upload functionality in this branch? 
- It should upload styles to http://mapbox.com/data for you.
- Please report back any problems or suggestions here.
- @samanpwbb Feel free to make UI improvements.

da button

**Comment by samanpwbb** [comment]
- User should not be able to click disabled buttons. We should prevent the action before they hit the error.
- Can we better educate user about what it means to add a Map ID to their project? First thought is to do this, but something more elegant may be better:
  screen shot 2014-04-02 at 6 12 27 pm
- Can the actions be reworked a little? I could see a visibility toggle working well:
  screen shot 2014-04-02 at 6 07 06 pm
- Put notice about uploading inline and disable the upload button for unauthorized users:
  screen shot 2014-04-02 at 6 19 50 pm
- Add form validation to map ID and baselayer ID (how is this working now?)
- Fix hover state for .disabled.quiet buttons (@samanpwbb)

**Comment by aaronlidman** [comment]
Cool. Right now the mapid doesn't do anything.
- Do we want that to be editable?
- Do we want to allow people to purposefully override their other maps?
- Is the 'package' button necessary after direct uploading is available?

I think we should make the mapid like /editor; displayed but not editable.

Baselayer id should be reworked, maybe moving it out of settings completely? resembling bookmarking and search. @edenh thoughts?

**Comment by yhahn** [comment]
Non-editable sounds good. For powerusers they can always change this directly in `project.yml`.

**Comment by edenh** [comment]
@aaronlidman Just curious, what does the baselayer ID have to do with the map ID in this upload context? If it's just that we have two 'id' fields in close proximity, I think we can design around that problem.

Placing the baselayer in settings was an intentional move over a map control. It enables setting the baselayer once and then have a seamless toggle experience, without having to expose the id every time you want to toggle.

**Comment by aaronlidman** [comment]
@edenh Yeah, it's just that they're both ids, potential confusion.

**Comment by nickidlugash** [comment]
I thought the map id doesn't get assigned until you upload to mapbox.com; how is there a map id to show already?

> Is the 'package' button necessary after direct uploading is available?

Not sure how deploying fonts will work in the future, but right now sometimes I package projects and don't upload them right away to mapbox.com because the necessary fonts haven't been deployed yet.

**Comment by aaronlidman** [comment]
@nickidlugash Yeah that's right, there is no mapid until upload. So the form will be blank before your first upload.

**Pull request merged**
