### PR TITLE
More example styles

### PR DESCRIPTION
**Pull request by yhahn**
Brings in 8 more example styles courtesy of @samanpwbb @amyleew @nickidlugash @tristen @ajashton @duncangraham @ian29.

### CODE REVIEW

**Comment by camilleanne** [comment]
screen shot 2014-09-09 at 2 17 30 pm

there are discrepancies in the capitalization of style names

**Comment by yhahn** [comment]
it's art

**Comment by ian29** [comment]
> it's art

lowercasing `wheatpaste` directly subverts a narrative of prescriptive grammar constructed to something something semiotic power

**Comment by amyleew** [comment]
@ian29  :clap:

**Comment by samanpwbb** [comment]
``` css
text-transform: capitalize;
```

**Pull request merged**
