### PR TITLE
Source UI adjustments

### LINKED ISSUE #844: [source + style] refresh quest
### Style usability adjustments:
- [x]  Divide saving to disk and refreshing into separate actions. `cmd+s` -> saves to disk, ~~`cmd+r`~~ `cmd+space` (for now?) -> refreshes map view.
- [x] Ensure alert notice is triggered if user tries to exit screen if work is unsaved (even if it's fully 'refreshed').
- [x] Add a visually disabled, 'saved' state to save button so user always knows if work is already fully saved:
  screen shot 2014-09-15 at 1 28 04 pm
- [x] Ensure export/upload options in settings panel are disabled unless map is fully saved. ~~(Combining this point with above point, we could rework export action to replace the save action in the sidebar when the map is saved.~~
- [x] If source or style is temporary, `cmd+s` action triggers save as dialog. All subsequent `cmd+s` actions trigger regular save.
### Source usability adjustments:
- [x]  Divide saving to disk and refreshing into separate actions. `cmd+s` -> saves to disk, ~~`cmd+r`~~ `cmd+space` (for now?) -> refreshes map view.
- [x] Ensure alert notice is triggered if user tries to exit screen if work is unsaved (even if it's fully 'refreshed').
- [x] Add a visually disabled, 'saved' state to save button so user always knows if work is already fully saved:
  screen shot 2014-09-15 at 1 28 04 pm
- [x] Ensure export/upload options in settings panel are disabled unless map is fully saved. ~~(Combining this point with above point, we could rework export action to replace the save action in the sidebar when the map is saved.~~
- [x] If style is temporary, `cmd+s` action triggers save as dialog. All subsequent `cmd+s` actions trigger regular save.
### Source-specific usability adjustments:
- [x] Auto refresh after clicking select button + reading the data (#536):
  screen_shot_2014-09-15_at_1_14_03_pm
- [x] Remove close button from layer panes, auto refresh after making changes (#545 / #544):
  screen_shot_2014-09-15_at_1_15_56_pm
- [x] ~~Auto refresh when clicking the hide or delete buttons in layer list, remove refresh option from list + refresh overlay from map:~~ **this does something different...**
  screen_shot_2014-09-15_at_1_20_27_pm
- [x] Add a refresh action to the SQL query input somewhere. _Not sure about this one - we may want to continue to rely on a save action here for viewing updates_:
  screen shot 2014-09-15 at 1 32 07 pm

### LINKED ISSUE #854: auto-centering is too far zoomed in
When adding new sources, especially those with broad geographic bounds, I usually end up with this screen:

screen shot 2014-09-17 at 4 09 48 pm

### LINKED ISSUE #865: Set changed if layer is deleted
After deleting layer, save button state should change and alert should appear on page exit.

### PR DESCRIPTION
**Pull request by samanpwbb**
This is ready. 
Fix #844
Fix #854
Fix #865

Other todos: 
- [x] Write tests
- [x] Collect feedback ( @ian29 / @karenzshea / @ajashton ) anyone up for a quick test run? cmd+r for refresh, cmd+s for proper save.

### CODE REVIEW

**Comment by GretaCB** [comment]
hey @samanpwbb , for loading, I added the following a while back: https://github.com/mapbox/mapbox-studio/pull/725

Is this what you're referring to? Or adding the load indicator to a different process?

**Comment by samanpwbb** [comment]
@GretaCB yeah, that loader is working. The problem occurs immediately after it disappears.

**Comment by ian29** [comment]
@samanpwbb 
- on forced "save as" is there a cheap way to indicate to a user that they are "saving as"? otherwise you're expecting the map to change and instead you get a filesystem modal. i did it 3 times before i remembered i was testing this branch
- this has the side effect: you add a layer you didnt mean to, try to remove and your immediately forced to save your empty project. maybe this is ok but i found it kind awkward, especially if you're just trying to throw some data into source editor to see what it looks like. im not sure of a workaround so maybe this is just me being whiny.

**Comment by yhahn** [comment]
@ian29 use ⌘+r ?

**Comment by ian29** [comment]
- when editing a source: zoom to a high z level, hit save to see your changes, see `center zoom value must be less than or equal to maxzoom` error. this is bad as it doesnt let me work on a source unless im within zoom bounds

**Comment by yhahn** [comment]
^^ this is a regression in mb-pages, I'll look into a fix there.

**Comment by samanpwbb** [comment]
With https://github.com/mapbox/mapbox-studio/commit/8bf3078887d17a9fd179ef510078a2734fca778d I adjusted when the loading state gets removed and I think that helps with the hangup i pointed out.

**Comment by samanpwbb** [comment]
yep, @yhahn done. I tested a few different approaches and this seems most trustworthy.

**Comment by samanpwbb** [comment]
:skull: I guess not.

**Comment by samanpwbb** [comment]
cf43d4537db9a4a37355e6e8448b30b5eef691a5 was legitimately a bad commit. 

https://github.com/mapbox/mapbox-studio/commit/b380bad986e9c118eb4fca418513651d858aa64e on the other hand refuses to behave any differently for me locally than mb-pages.

Here's where it's failing: https://travis-ci.org/mapbox/mapbox-studio/jobs/35742860#L1368 - I can't get this to fail for me locally.

**Comment by yhahn** [comment]
Looks great - the serverside test fail is hard to explain and I can't reproduce locally after dozens of runs  on while loop : |

Going to merge and let rare test fails get squashed in follow ups.

**Pull request merged**
