### PR TITLE
UI for user fonts

### LINKED ISSUE #991: Any news on adding custom Fonts?
any news when the next version will be able to handle custom fonts? We are at a standstill until we can load our own fonts.
Thanks..

### LINKED ISSUE #996: Link font-directory to help
image

It would be helpful to link the text `font-directory` to the appropriate help item.

### LINKED ISSUE #999: Add UI for displaying user-provided font names

### PR DESCRIPTION
**Pull request by samanpwbb**
Display fonts that are in the directory user specified:
screen shot 2014-11-07 at 6 29 11 pm

Empty state: 
screen shot 2014-11-07 at 8 09 36 pm
#### Todo:
- [x] Add user fonts to a fixture and test
#### Question:

How should we handle updating this list? Right now, here's what happens:
- In code, list is updated whenever map is saved: https://github.com/mapbox/mapbox-studio/compare/userfontui?expand=1#diff-9d7bf77fe41e8ddb12a4c326f2f94bd0R780
- Style provides updates to list only when: 
  1. `font-directory` changes in user's carto
  2. user loads a new style
  3. Mapbox studio is killed and started again

So, that template insertion code rarely ever does anything useful, but it runs frequently. I see three legitimate options:
1. Check for changes in font list and only do the replace if font list changes.
2. Remove this refresh and update the font list only on restart.
3. Also update the font list when user makes a change to the fonts in the font directory.

The perfectionist designer in me wants to do 3 but the simplest solution is probably 2.

fix  #999
fix #996
fix #991 

cc: @yhahn

### CODE REVIEW

**Comment by yhahn** [comment]
@samanpwbb just published tilelive-vector@3.0.2 and tilelive-bridge@1.2.1 that should fix the xml update issue.

**Comment by samanpwbb** [comment]
This is ready to go.

**Comment by springmeyer** [comment]
\o/

**Comment by wboykinm** [comment]
dopitydopedopedope

**Comment by yhahn** [comment]
@samanpwbb awesome work on this. Only tweaked a couple small code style things and added one more test for good measure.

**Pull request merged**
