### PR TITLE
Fix query assumptions with mapnik 3.4.18

### PR DESCRIPTION
**Pull request by jakepruitt**
Fixes an issue in the node-mapnik 3.4 series where the vector-tile decoder was assuming the layer tags came before geometries, which was breaking when reading version 2 tiles where that assumption is not guaranteed.

This should be released as soon as possible, since it's blocking the launch of V2 tiles.

cc/ @springmeyer @rclark @yhahn @flippmoke @GretaCB

### CODE REVIEW

**Comment by jakepruitt** [comment]
@BergWerkGIS Do you think I could get your help getting this branch passing on AppVeyor? We'll want to release this in the next day or so, and it would be amazing to have your help confirming it works on Windows.

**Comment by wilhelmberg** [comment]
I'll have a look. 
Weird, the `node@0.12.7` builds seem to pull in `node@4.4.1`:
https://ci.appveyor.com/project/Mapbox/mapbox-studio-classic/build/1.0.105/job/luk6lac32rjn4m9e#L64

**Comment by wilhelmberg** [comment]
Hm, might take a bit. Works for me locally.

**Comment by wilhelmberg** [comment]
@jakepruitt AppVeyor all :white_check_mark: again.
https://ci.appveyor.com/project/Mapbox/mapbox-studio-classic/build/1.0.111

You might want to look into duplicate `node-pre-gyp`s:

https://ci.appveyor.com/project/Mapbox/mapbox-studio-classic/build/1.0.111/job/i4qgww56wcr5rhqw#L71

```
> npm dedupe node-pre-gyp

npm WARN unavoidable conflict node-pre-gyp { 'C:\projects\mapbox-studio-classic\node_modules\gdal\node_modules\node-pre-gyp': '0.6.15',
npm WARN unavoidable conflict   'C:\projects\mapbox-studio-classic\node_modules\mbtiles\node_modules\sqlite3\node_modules\node-pre-gyp': '0.6.9',
npm WARN unavoidable conflict   'C:\projects\mapbox-studio-classic\node_modules\mapnik\node_modules\node-pre-gyp': '0.6.24',
npm WARN unavoidable conflict   'C:\projects\mapbox-studio-classic\node_modules\node-pre-gyp': '0.6.9' }
npm WARN unavoidable conflict Not de-duplicating
```

**Comment by jakepruitt** [comment]
@BergWerkGIS what are the risks of shipping with dupe `node-pre-gyp`s? It looks like fixing it would involve upgrading a lot of dependencies and possibly doing a patch release to the mapnik-omnivore 7.2 series.

@yhahn any opinion here?

**Comment by springmeyer** [comment]
Don't worry about node-pre-gyp dupes. The idea behind avoiding dupes is to save space in the final download, but this is not critical at all. /cc @BergWerkGIS @jakepruitt

**Pull request merged**
