### PR TITLE
atom-shell child process

### PR DESCRIPTION
**Pull request by yhahn**
Sets up desktop app packaging for mapbox-studio as a child process of atom-shell. node-based execution is still possible/supported.
- [x] @yhahn use travis to do mac os x .app signing
- [x] custom Info.plist for OS X app
- [x] @camilleanne Mac OS X menu
- [x] @camilleanne handle downloads/external links in atom-shell, blocked by https://github.com/atom/atom-shell/issues/542
- [x] **PUNT** ~~review windows uninstaller~~ https://github.com/mapbox/mapbox-studio/issues/611

### CODE REVIEW

**Comment by incanus** [comment]
Finding some OS X identity crisis issues here while working on code signing, mostly holdovers from Atom identify. 
1. Code signing outputs: 
   
   ``` bash
   Mapbox Studio.app: signed bundle with Mach-O thin (x86_64) [com.github.atom]
   ```
2. Binary is named `Atom`, which will affect process list. 
   
   screen shot 2014-08-04 at 10 18 28 am
3. `Info.plist` contains Atom references. 
   
   screen shot 2014-08-04 at 10 18 37 am
4. App menu is generic / Atom holdover. 
   
   screen shot 2014-08-04 at 10 20 21 am
   
   screen shot 2014-08-04 at 10 20 39 am
   
   screen shot 2014-08-04 at 10 20 47 am
5.  Web developer tools can be activated. 
   
   screen shot 2014-08-04 at 10 21 58 am
6. No menu item / keyboard shortcut for full screen mode.

**Comment by yhahn** [comment]
I'm ok with all but 4 for now. We don't need to hide the fact we're using Atom at the system level.

For 4 looks like there's some APIs we can poke around for overriding the app menu -- @camilleanne want to poke at this today? https://github.com/atom/atom-shell/blob/master/docs/api/menu.md#class-menu

**Comment by incanus** [comment]
Ok. I'm not sure if item 2 (binary name) will interfere with running instances of Atom, though. Item 3 (`Info.plist`) should at least change the bundle ID (`com.github.atom`) as this will overwrite preferences on disk for anyone using Atom and stuff like that, besides being very bad form. It's something on par with registering the domain name `github-apps.com` and using it for our stuff ;-)

**Comment by yhahn** [comment]
Good to know -- do you want to poke the maintainer of atom-shell @zcbenz in https://github.com/atom/atom-shell/issues about the intended distribution flow here -- ie. BYOI (bring your own info.plist) ?

**Comment by incanus** [comment]
You probably just want to modify `Info.plist` yourself as part of bundling. 
- https://github.com/atom/atom-shell/issues/477#issuecomment-50113357
- https://github.com/atom/atom-shell/issues/89#issuecomment-24213224

You can modify property lists directly as text or with `/usr/bin/defaults` on OS X.

**Comment by yhahn** [comment]
:+1:

**Comment by yhahn** [comment]
Ignoring appv fail which is unrelated atm. Merging!

**Pull request merged**
