### PR TITLE
Export static

### PR DESCRIPTION
**Pull request by camilleanne**
adds 2 endpoints for exporting static maps

### CODE REVIEW

**Comment by yhahn** [comment]
@camilleanne :ship:

**Comment by lxbarth** [comment]
@camilleanne - what does this patch do?

**Comment by camilleanne** [comment]
@lxbarth it adds two endpoints for exporting print resolution static maps.  We recently updated tilelive-vector https://github.com/mapbox/tilelive-vector/pull/57 to support tiles of greater dimensions as determined by scale, and so now it's possible to export 1024x1024 vector tiles. A tile at this size is the equivalent of 288 dpi when constrained to the same space as a traditional 256x256 tile, or print resolution (almost)! By gathering a list of tiles within a desired area, we can stitch them together to create a high resolution static map suitable for prints or anything that needs to be BIG.

it uses [abaculus](http://github.com/mapbox/abaculus)

When tm2 is running, the end points are:
1)  `http://localhost:3000/static/{zoom}/{w},{s},{e},{n}@{scale}x.{format}?id={tmstyle}`
This generates a static map based on geographic coordinates where the coordinates follow the `[w,s,e,n]` pattern. This is anticipating an eventual UI for exporting these maps, and is consistent with [node-sphericalmercator](https://github.com/mapbox/node-sphericalmercator) and the GeoJSON spec for [bounding boxes](http://geojson.org/geojson-spec.html#bounding-boxes)

2)   `http://localhost:3000/static/{zoom},{x},{y}/{px}x{py}@{scale}x.{format}?id={tmstyle}`
This generates a static map based on center coordinate and pixel boundaries where the `x`,`y` is `long`,`lat` at the center of the map. This is (mostly) consistent with Mapbox's current static map API.

**Comment by lxbarth** [comment]
Thanks @camilleanne

**Pull request merged**
