### PR TITLE
Enable to browse other drives than C:

### PR DESCRIPTION
**Pull request by wilhelmberg**
refs #824

### CODE REVIEW

**Comment by yhahn** [comment]
@BergWerkGIS want to add a test for this, in particular one that calls `tm.dirfiles` at the root dir? You can conditional your assertions in the test based on the platform as well.

https://github.com/mapbox/mapbox-studio/blob/mb-pages/test/tm.test.js#L105

**Comment by wilhelmberg** [comment]
@yhahn 

test added
https://github.com/mapbox/mapbox-studio/blob/windrives/test/tm.test.js#L135-L151

shoud work on most systems, as it is very uncommon to **not** have a `C:` drive.

**Comment by springmeyer** [comment]
@BergWerkGIS - great. Can you watch for when #1267 is merged and then re-create this pull request with just your additions? We are aiming for a release this weekend or early next week based on #1267, and then it would be great to follow with new features like this.

**Comment by wilhelmberg** [comment]
@springmeyer I merged `node-mapnik-3.2.0`, because of https://github.com/mapnik/node-mapnik/issues/427.

What is the planed procedure?
Merge this one into `mb-pages` after `node-mapnik-3.2.0` or this one into `node-mapnik-3.2.0` and then into `mb-pages`?

Also, how to procede with https://github.com/mapbox/mapbox-studio/pull/1265 ?

**Comment by wilhelmberg** [comment]
merged into current dev branch:
https://github.com/mapbox/mapbox-studio/pull/1435

**Pull request closed without merging**
