### PR TITLE
Space walk

### PR DESCRIPTION
**Pull request by yhahn**
- Renames all our testing style/source fixtures to include a space.
- Adds tests to ensure spaces are not urlencoded at any point when loading or caching a style/source project.
- Adds `middleware.normalizePaths` to consolidate path normalization logic on all requests. After this middleware all code should expect:
  - No urlencoding in paths. Spaces will be spaces. etc.
  - On windows, all path separators will be normalized to `/`
  - On windows, all drivenames will be lowercasified
  
  Read: other parts of mapbox-studio should not be engaged in path normalization.
### Next up
- [x] make sure tests pass on travis/appveyor
- [x] manual testing on each platform, esp Windows export+download bug + source => style creation

cc @springmeyer @camilleanne @mtirwin

### CODE REVIEW

**Comment by springmeyer** [comment]
Currently 5 test failures on appveyor. First one here seems to capture the issue:

```
not ok 179 should be equal
  ---
    operator: equal
    expected:
      'tmsource://C:\\projects\\mapbox-studio\\test/fixtures-local source'
    actual:
      'tmsource:///projects/mapbox-studio/test/fixtures-local source'
  ...
```

https://ci.appveyor.com/project/Mapbox/mapbox-studio/build/1.0.1891/job/hihf6ky6tkth1u74#L1300

**Comment by yhahn** [comment]
Ok, I've tested on Windows:
- [x] tests passing
- [x] export => download flow in repo named "Mapbox Studio"
- [x] local source => style creation in repo named "Mapbox Studio"

### Next actions
- [x] dev app build
- [ ] @yhahn manual testing of app built on Windows
- [ ] @springmeyer or @camilleanne manual testing of app built on OS X
- [ ] merge + releasetown?

**Comment by wilhelmberg** [comment]
@springmeyer yeah, you are right, just `win32`.

I wanted to make sure and I searched Google and found this (http://shapeshed.com/writing-cross-platform-node/) and the guy uses `win64`.

Now I've looked thru nodejs code on Github and couldn't find `win64`.

**Comment by yhahn** [comment]
Ok, font previews should be fixed now.

I've run into this in my windows testing, but I think a fix is more appropriate in a different branch/PR: https://github.com/mapbox/mapbox-studio/commit/bb51ead49b314ff2fea30aa3638c181dc08767ff#commitcomment-10325199

I think this branch is ready to merge now, but sounds like we have some more things to hit before we want to roll a release.

@springmeyer @camilleanne @mtirwin

**Comment by yhahn** [comment]
@springmeyer @camilleanne ok I have a build that I feel confident about on Windows. Per usual, it seems to me like there were multiple issues involved, but I've boiled down the issue to two parts. In my testing export download would _sometimes_ work and sometimes not. Now with both issues addressed I've yet to hit a export hang/fail in the three contexts I've been testing:
- Start atom.exe from shell, dev mode (e.g. resources/app is my repo)
- Start atom.exe from explorer, dev mode
- Start Studio after fresh install of published installer

App actions:
- export mbtiles, download to disk (Save As dialog) x2+ times
- static image export, download to disk (Save As dialog) x2+ times

_Sometimes the hang would only occur on the second time doing one of these actions..._

---

### Hang 1: no request response

Callback to http.get/http.request was never called (https://github.com/mapbox/mapbox-studio/blob/space-walk/app/atom.js#L69)
- **Fix:** `remote.require` for fs + http modules.
- **Lines:** https://github.com/mapbox/mapbox-studio/blob/2098e14a7aeb68b14064e37e4cc0c986f461b3dd/app/atom.js#L40-L44
- **Notes:** The [docs around remote/when to use it](https://github.com/atom/atom-shell/blob/master/docs/api/remote.md#remote) seem pretty inconsistent with what atom-shell allows you to do, e.g. we could require fs/http without remote and get away with a lot on OS X + linux. Switching to remote on windows fixes the http request callback issue.

### Hang 2: UI finish state never called

The modal.close + finish state of the download was never called -- e.g. the file would be downloaded to disk but the UI would still show spinner (https://github.com/mapbox/mapbox-studio/blob/space-walk/app/atom.js#L65)
- **Fix:** add listener for `finish` event prior to `pipe()`
- **Lines:** https://github.com/mapbox/mapbox-studio/blob/2098e14a7aeb68b14064e37e4cc0c986f461b3dd/app/atom.js#L76-L82
- **Notes:** This one's a bit wacky -- in normal node land you'd expect I/O to occur in the next tick allowing you to do this:
  
  ```
  res.pipe(writeStream).on('finish', handler);
  ```
  
  And `handler` would be registered before the `finish` event is called. _This is apparently not a safe assumption in windows + atom-shell and I would love to know why._ Still digesting on any further conclusions here...

---

### Next actions
- [ ] @springmeyer @camilleanne review
- [ ] merge, releasetown
- [ ] post-mortem... try to isolate testcases for atom-shell issues

**Comment by springmeyer** [comment]
Incredible work @yhahn.
- Tested on Win 7 64 bit local VM
- Downloading .mbtiles for a vector source in both the app and via chrome worked great.

But, I was unable to test exporting static maps: I ran into #1278 (not sure if this is new in space-walk).

One small comment wrt to mbtiles export: I find the `Exporting` and `Export complete` modal odd because it is being presented after the download (https://github.com/mapbox/mapbox-studio/pull/1267/files#diff-0e91f40605f9cd51ab8837b0d98ad66eR101). Should it instead say `Downloaded successfully to c://the/path/the/file/was/saved.mbtiles`? Or maybe we don't need a modal at all?

**Pull request merged**
