### PR TITLE
Detect extent

### PR DESCRIPTION
**Pull request by GretaCB**
Solves https://github.com/mapbox/mapbox-studio/issues/883

Transforms other projections to WGS84 to get true extent instead of defaulting to global extent.

### CODE REVIEW

**Comment by GretaCB** [comment]
@yhahn Reluctant to merge because I dont want to contaminate mb-pages with https://github.com/mapbox/mapbox-studio-internal/issues/140

**Comment by yhahn** [comment]
@GretaCB :+1:

**Comment by wboykinm** [comment]
FYI I just pulled the updates and now I'm getting `Cannot read property 'shape' of undefined` for any source I try to create, including the shapefiles that might have benefitted from this PR.

**Comment by yhahn** [comment]
@wboykinm any useful line numbers in the logs? And you cleared out `node_modules` and re `npm install`'d to get @GretaCB's upstream changes in mapnik omnivore?

**Comment by wboykinm** [comment]
Forgot to clear modules. That nailed it, and the export went perfectly at z10 (<1min), now using it to [render at z15](https://api.tiles.mapbox.com/v4/faraday2.c77ab684/page.html?access_token=pk.eyJ1IjoiZmFyYWRheTIiLCJhIjoiTUVHbDl5OCJ9.buFaqIdaIM3iXr1BOYKpsQ#15/40.7084/-74.0046). Thanks for all the great work guys!

**Comment by GretaCB** [comment]
:+1:

**Pull request merged**
