### PR TITLE
Baselayer toggle

### PR DESCRIPTION
**Pull request by edenh**
baselayer

### CODE REVIEW

**Comment by samanpwbb** [comment]
@edenh can you think of an elegant way to allow me to hide my map style? My original desire for this feature: being able to compare a basemap style to satellite imagery. As it stands, this feature isn't helpful when working on basemaps because the basemap 100% obscures the specified baselayer.

**Comment by edenh** [comment]
I think it's safe to assume that users will comment out map backgrounds to view the baselayer. There are two possible ways I can think to get around this issue, which are not good solutions. 
- Automatically 'dimming', the existing style, which I think is too aggressive and potentially confusing.
- Placing the baselayer _above_ the existing layer at a lower opacity. I don't think this is a particularly good idea either.

Did you have anything else in mind?

**Comment by samanpwbb** [comment]
The only alternative that makes sense to me is to move baselayer into the layers panel, add layer visibility toggle like we have in source mode. Happy to just leave this as-is for now and comment out things if you think this is introducing unnecessary complexity to the layers panel though.

**Comment by yhahn** [comment]
Don't do this. Mixing apples and oranges.

**Pull request merged**
