### PR TITLE
Split project settings from style/source browsing

### PR DESCRIPTION
**Pull request by yhahn**
It was a fun experiment but having a consolidate settings/browse action never felt right to me. This takes things back a step to something more conventional.

@samanpwbb review + feedback?

pr

### CODE REVIEW

**Comment by aaronlidman** [comment]
Great, I like it. Only criticism is that clicking my face isn't the most intuitive for getting to styles/sources, not sure what is tho.

**Comment by yhahn** [comment]
ya classic avatar overloading

**Comment by edenh** [comment]
Creeping here. I like this move a lot. Making the style/source name trigger the browse modal can help clarify the action.

**Comment by samanpwbb** [comment]
Associating browse UI with user profile actually makes a lot of sense to me. Full :+1: from me. This is _your_ inventory. I would not associate this with the style/source name. If anything, name should bring up settings.

**Comment by yhahn** [comment]
Cool will merge once @aaronlidman 's modal work is in. We can iterate on whether the project name should do anything (it's not clickable atm).

**Comment by samanpwbb** [comment]
Kind of glad you killed the weird blue too. It totally wore out on me a couple weeks ago.

**Comment by ajashton** [comment]
:+1:

**Pull request merged**
